### ISSUE TITLE
Download of Survey responses stops when retrieving Japanese language surveys

### ISSUE THREAD

**Issue by Delkine** [ropensci/qualtRics#73] opened 2018-03-14 17:34 UTC
We have a R script that we use to download English Language surveys.  We also have a Japanese language version of the same survey with a different surveyid.  The qualtRics "get survey" works perfectly to download responses for the English surveyid but the same script (only changing the surveyid and RDS name) starts to download and then stops with only 2 or 3 surveys downloaded or none at all.  There are over 300 surveys collected and they can be downloaded manually from the Qualtrics site with no problems.   We have been able to get the script to work perfectly on several windows 10 computers on 2 different networks.  The server we are using is an older machine and has a Windows 7 operating system behind a corporate secure firewall.  The English language survey downloads without problems on the same server but fails with the Japanese version.

Do you know of any issues that would affect the downloading of surveys that have Japanese Characters in open-ended responses? Would white listing the Qualtrics ports help? How about the API address?

**Comment by JasperHG90** [comment] 2018-03-27 18:18
Hi Delkine,

It'd be helpful if you could share a subset of the data so I can test it. I don't have a lot of experience with importing languages other than English, but it's likely that there's an encoding issue.

Thanks,

Jasper. (jasperginn@gmail.com)

**Comment by juliasilge** [comment] 2019-03-26 20:26
Hello there @Delkine! I am the new maintainer for this package. 👋 Since the script you have works well on machines with newer versions of Windows but does not work well with an older version of Windows, and it is actually the **download itself** that is hanging, there isn't anything we're going to be able to change within the R code of this package to fix this problem. This sounds like a system-level problem instead of a problem with the R package, and the older Windows machine can't handle the encoding required for Japanese. Encoding on Windows is famously troublesome! I'm going to close this because the problem is not related to much that I as a maintainer can change.

**Closed by juliasilge** 2019-03-26 20:26 UTC
